2024-03-11 22:22:42,194 AutoFE.py:35 __init__ INFO | Namespace(cuda='0', epochs=300, ppo_epochs=20, episodes=2, file_name='SPECTF', mode='classify', model='xgb', metric='f1', seed=1, train_size=0.7, cv=5, shuffle=False, d_model=128, d_k=32, d_v=32, d_ff=64, n_heads=6, worker=1, steps_num=3, lr=0.0001, entropy_weight=0.0001, baseline_weight=0.95, gama=0.9, gae_lambda=0.95, batch_size=4, c_columns=['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43'], d_columns=[], target='label')
2024-03-11 22:22:42,194 AutoFE.py:36 __init__ INFO | File name: SPECTF
2024-03-11 22:22:42,194 AutoFE.py:37 __init__ INFO | Data shape: (267, 45)
2024-03-11 22:22:42,210 AutoFE.py:90 set_cuda INFO | Use device: 0, cuda:0, NVIDIA GeForce RTX 4060 Laptop GPU
2024-03-11 22:22:42,210 AutoFE.py:80 __init__ INFO | Done AutoFE initialization.
2024-03-11 22:22:42,422 AutoFE.py:103 fit_attention INFO | score_b=0.7976939203354297, scores_b=[0.83333333 0.77777778 0.77358491 0.75471698 0.8490566 ]
2024-03-11 22:24:47,520 main_ppo.py:80 <module> INFO | Traceback (most recent call last):
  File "D:\python files\pythonProject3\PPO_transformer_lstm\main_ppo.py", line 76, in <module>
    autofe.fit_attention(args)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\AutoFE.py", line 152, in fit_attention
    w = multiprocess_reward(args, worker, c_columns, d_columns, scores_b, mode,model, metric, x_d_onehot, df_t.values, df_d_labelencode)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\feature_engineer\training_ops.py", line 78, in multiprocess_reward
    repeat_ratio = cal_repeat_actions(len(c_columns), worker_c.ff)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\feature_engineer\training_ops.py", line 111, in cal_repeat_actions
    eval(list(dic.keys())[0]).extend(tuple(x) for x in list(dic.values())[0])
  File "<string>", line 1, in <module>
NameError: name 'combine' is not defined

2024-03-11 22:24:47,520 main_ppo.py:82 <module> INFO | Total cost time: 125.3299 s.
