2024-03-09 23:39:31,376 AutoFE.py:34 __init__ INFO | Namespace(cuda='0', epochs=300, ppo_epochs=20, episodes=3, file_name='SPECTF', mode='classify', model='xgb', metric='f1', seed=1, train_size=0.7, c_columns=['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43'], d_columns=[], target='label')
2024-03-09 23:39:31,376 AutoFE.py:35 __init__ INFO | File name: SPECTF
2024-03-09 23:39:31,376 AutoFE.py:36 __init__ INFO | Data shape: (267, 45)
2024-03-09 23:39:32,907 AutoFE.py:90 set_cuda INFO | Use device: 0, cuda:0, NVIDIA GeForce RTX 4060 Laptop GPU
2024-03-09 23:39:32,907 AutoFE.py:80 __init__ INFO | Done AutoFE initialization.
2024-03-09 23:52:46,351 main_ppo.py:64 <module> INFO | Traceback (most recent call last):
  File "D:\python files\pythonProject3\PPO_transformer_lstm\main_ppo.py", line 60, in <module>
    autofe.fit_attention(args)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\AutoFE.py", line 103, in fit_attention
    score_b, scores_b = self._get_cv_baseline(df, args, mode, model, metric)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\AutoFE.py", line 206, in _get_cv_baseline
    if not args.shuffle: args.seed = None
AttributeError: 'Namespace' object has no attribute 'shuffle'

2024-03-09 23:52:47,165 main_ppo.py:66 <module> INFO | Total cost time: 795.4248 s.
