2023-11-06 17:57:37,012 autofe.py:52 __init__ INFO | Namespace(cuda='0', train_size=0.7, epochs=120, ppo_epochs=20, episodes=10, lr=0.0001, entropy_weight=0.0001, baseline_weight=0.95, gama=0.9, gae_lambda=0.95, batch_size=4, d_model=128, d_k=32, d_v=32, d_ff=64, n_heads=6, worker=1, steps_num=3, combine=True, preprocess=False, seed=1, cv=5, cv_train_size=0.7, cv_seed=1, split_train_test=False, shuffle=False, enc_c_pth='', enc_d_pth='', mode='classify', model='xgb', metric='f1', file_name='lymphography', c_columns=['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17'], d_columns=[], target='label')
2023-11-06 17:57:37,012 autofe.py:53 __init__ INFO | File name: lymphography
2023-11-06 17:57:37,013 autofe.py:54 __init__ INFO | Data shape: (148, 19)
2023-11-06 17:57:37,024 autofe.py:122 set_cuda INFO | Use device: 0, cuda:0, NVIDIA GeForce RTX 4060 Laptop GPU
2023-11-06 17:57:37,024 autofe.py:112 __init__ INFO | Done AutoFE initialization.
2023-11-06 17:57:37,028 autofe.py:435 _get_cv_baseline INFO | Start getting CV baseline...
2023-11-06 17:57:37,391 autofe.py:142 fit_attention INFO | score_b=0.8318043385275983, scores_b=[0.88518519 0.84987469 0.85026455 0.74544366 0.82825362]
2023-11-06 17:57:37,395 main_attention.py:91 <module> INFO | Traceback (most recent call last):
  File "D:\python files\pythonProject3\FETCH\main_attention.py", line 88, in <module>
    autofe.fit_attention(args)
  File "D:\python files\pythonProject3\FETCH\autofe.py", line 157, in fit_attention
    df_c_encode, df_d_encode = df.loc[:, c_columns + [target]], df.loc[:, d_columns + [target]]
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\indexing.py", line 1256, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\indexing.py", line 924, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\indexes\base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\indexes\base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['V0'] not in index"

2023-11-06 17:57:37,401 main_attention.py:93 <module> INFO | Total cost time: 0.3895 s.
